version: 2.1
jobs:
  Dependecias:
    working_directory: ~/Practica 3.2
    docker:
      - image: circleci/open/jdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn dependency:go-offline
  Compilar:
    working_directory: ~/Practica 3.2
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn complie -e -X
  Testing:
    working_directory: ~/Practica 3.2
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps: 
      - run:
        name: Las Pruebas
        comand: 
          echo 'Haciendo pruebas'
      - ckeckout
      - run: mvn test -e -X
  Run-Package:
    working_directory: ~/Practica 3.2
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn package -e -X
